### ISSUE TITLE
Strange behavior typing immediately after reloading

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#76]
Looking at https://developer.mozilla.org/en-US/docs/User:schalkneethling:push

If you load the page, the start typing without clicking in the box, strange things happen. This is from typing "12345": http://imgur.com/a/TcmMH

Also, the arrow keys don't work in this situation, and also, the row isn't highlighted.

If I move the cursor, then put it back there, this behavior goes away.

**Comment by schalkneethling** [comment]
Resolved in https://github.com/mdn/interactive-examples/pull/81

**Comment by wbamberg** [comment]
I'm still seeing this, for example here: https://mdn.github.io/interactive-examples/pages/js/array-push.

**Comment by schalkneethling** [comment]
Interesting, so this is a `codemirror` error causing the problem:

```
codemirror.js:1 Uncaught Error: There is no line 40 in the document.
    at k (codemirror.js:1)
    at rs.getLineHandleVisualStart (codemirror.js:1)
    at Oo.getLineHandleVisualStart (codemirror.js:1)
    at r (codemirror.js:1)
    at i (codemirror.js:1)
    at Ne (codemirror.js:1)
    at ai (codemirror.js:1)
    at fi (codemirror.js:1)
    at Li (codemirror.js:1)
    at xi (codemirror.js:1)
```

Will have a look around to see if this is perhaps a known bug, and we perhaps need to update to the latest version of CodeMirror.

**Comment by schalkneethling** [comment]
Closing this one out again as I do not see the same behaviour with Prism. Should we in the end switch back to CodeMirror and the issues shows up again, we can open this up again.
