### ISSUE TITLE
@font-face doesn't work with Shadow DOM?

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#887]
Related to https://github.com/mdn/interactive-examples/issues/881: the `input` examples generally use `.output` to set the font to one that we loaded using `@font-face`. But changing this seems to indicate that the custom font specified using `@font-face` isn't being loaded any more.

For example, in https://interactive-examples.mdn.mozilla.net/pages/tabbed/input-file.html, changing 

```
.output {
    font: 1rem 'Fira Sans', sans-serif;
}
```

to

```
legend, label {
    font: 1rem 'Fira Sans', sans-serif;
}
```
... you can see that the rules are having an effect, but `'Fira Sans'` is not being used.

This is in both Firefox(with the shadow DOM pref on) and Chrome.

**Comment by wbamberg** [comment]
Weirdly this seems to work in production: https://interactive-examples.mdn.mozilla.net/pages/tabbed/input-email.html, just not in the local testing server.

**Comment by wbamberg** [comment]
It looks like this is still not loading the custom fonts. In this example "He-Man" should use [molot](https://www.fontsquirrel.com/fonts/Molot), and "Skeletor" should use [rapscallion](https://www.dafont.com/rapscallion.font).

<img width="442" alt="screen shot 2018-07-12 at 2 13 39 pm" src="https://user-images.githubusercontent.com/432915/42659671-d5577bdc-85dd-11e8-81c8-6e2ce8addef6.png">

**Comment by schalkneethling** [comment]
I tested this on production at:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/caption

Tested in Chrome, Fx Release, Developer, Nightly, as well as Safari. They all display as below:

<img width="1056" alt="screen shot 2018-07-13 at 11 51 25" src="https://user-images.githubusercontent.com/10350960/42685520-74177e2e-8693-11e8-8b0c-a3573b8b82f2.png">

Perhaps cache because of the experiment going on at the moment with the longer lived cache? Try accessing and see if that busts the cache:

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/caption?v=2

**Comment by wbamberg** [comment]
Oh yes! Works great. Must have been the cache :).

**Comment by drochgenius** [comment]
Hi,

I just found out the `@font-face` doesnt load the fonts if it's within a Shadow DOM. Looking at this thread, and in the Shadow DOM v1 spec I couldn't find any reference to this limitation.

Basically, I'd like to know if this is by design, or a current browser restriction that will eventually be fixed? If it's by design, anybody knows where in the spec I can find this documented?

Thanks

**Comment by schalkneethling** [comment]
@drochgenius Here is some reading for reference:

https://robdodson.me/at-font-face-doesnt-work-in-shadow-dom/
https://bugs.chromium.org/p/chromium/issues/detail?id=336876

Looks like it might be a bug that is fixed in Chrome, will need to test to confirm, and also test in Firefox. Hoping the Edge folks will have this working from the get go.

**Comment by drochgenius** [comment]
Thanks @schalkneethling !
Exactly what I was looking for.

**Comment by kleinfreund** [comment]
@schalkneethling I’m confused. That bug wasn’t fixed,right? I can’t load fonts with a `@font-face` rule placed in the shadow DOM.

**Comment by schalkneethling** [comment]
> @schalkneethling I’m confused. That bug wasn’t fixed,right? I can’t load fonts with a `@font-face` rule placed in the shadow DOM.

@kleinfreund I have not tested this in some time but, as far as I am aware, this is still the case.

**Comment by migudev** [comment]
@schalkneethling The only workaround to this is putting the webfont in the `index.html` and import the css through a `link` tag.

**Example**

```html
<!-- index.html -->
<link rel="preload" href="/css/icons.css" as="font" />
<link rel="stylesheet" href="/css/icons.css" />
```

```javascript
render() {
  return html`
    <link rel="stylesheet" href="/css/icons.css" />
    <i class="icon-home"></i>
  `
}
```

**Comment by alx696** [comment]
@schalkneethling  Must define `@font-face` in the html:

```
    @font-face {
      font-family: "iconfont";
      src: url('../iconfont/iconfont.woff') format('woff');
    }
```
> Google Chrome 76.0.3809.132

Firefox 68.0.2 not show anything even define `@font-face` in the html.

**Comment by Mangor1no** [comment]
This problem still occurs on both Chrome and Firefox. 

Chrome version: 80.0.3987.132 (64 bit) (cohort: Stable)
Firefox version: 73.0.1 (64 bit)

**Comment by eafiontzi** [comment]
I have the exact same problem, building a web component using Angular Custom Elements which includes custom `@font-face` . If I use `encapsulation: ViewEncapsulation.ShadowDom` the fonts are not appearing, instead without shadowDom and using `:host ::ng-deep` works fine.

**Comment by xmarkclx** [comment]
Can confirm. Problem still exists.

**Comment by drachehavoc** [comment]
2021 and the problem persists...

**Comment by Amaimersion** [comment]
Problem still exists

**Comment by Jore** [comment]
Problem still persists

**Comment by teoli2003** [comment]
There is a misunderstanding here. This issue is about a problem we had in our interactive examples, that was fixed in 2018.

This issue is not about a limitation for `@font-face` with Shadow DOM on the browser side. In other words, we worked around the real issue but we are not the place to fix the underlying problem, you need to report the issue to browser vendors and/or spec editors, whatever is the most relevant.

@schalkneethling Can we prevent new comments in this issue as they are only noise for us? We can't act to help people coming here in good faith.

**Comment by coolcorexix** [comment]
`@font-face` is still not working in Shadow DOM as of Aug 2024 but it is relatively easy to work around: just register the new font outside of the Shadow DOM and the element using that font inside Shadow DOM will acknowledge it.
